version: '3.8'

services:
  web:
    build: .
    container_name: home_inventory_web
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=home_inventory
      - DB_USER=demo
      - DB_PASSWORD=demo
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: home_inventory_db
    environment:
      POSTGRES_USER: "demo"
      POSTGRES_PASSWORD: "demo"
      POSTGRES_DB: "home_inventory"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
